[package]
name = "rust_structures"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_structures"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }